blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogUpdateView,
    BlogListView,
    BlogDetailView,
    BlogDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<slug>/", BlogDetailView.as_view(), name="blog_view"),
    path("update/<slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<slug>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="index")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from mailing.apps import MailingConfig
from mailing.views import (
    MailingCreateView,
    MailingDetailView,
    MailingDeleteView,
    MailingUpdateView,
    MailingListView,
    ClientCreateView,
    ClientListView,
    ClientDetailView,
    ClientUpdateView,
    ClientDeleteView,
    MessageCreateView,
    MessageListView,
    MessageDetailView,
    MessageUpdateView,
    MessageDeleteView,
    IndexView, AttemptListView,
)

app_name = MailingConfig.name

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("mailings/", MailingListView.as_view(), name="mailing_list"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("update/<int:pk>", MailingUpdateView.as_view(), name="mailing_update"),
    path("delete/<int:pk>", MailingDeleteView.as_view(), name="mailing_delete"),
    path(
        "mailing/<int:pk>",
        cache_page(60)(MailingDetailView.as_view()),
        name="mailing_detail",
    ),
    path("client_create/", ClientCreateView.as_view(), name="client_create"),
    path("client_list/", ClientListView.as_view(), name="client_list"),
    path(
        "client_detail/<int:pk>/",
        cache_page(60)(ClientDetailView.as_view()),
        name="client_detail",
    ),
    path("client_update/<int:pk>/", ClientUpdateView.as_view(), name="client_update"),
    path("client_delete/<int:pk>/", ClientDeleteView.as_view(), name="client_delete"),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path(
        "message_detail/<int:pk>/",
        cache_page(60)(MessageDetailView.as_view()),
        name="message_detail",
    ),
    path(
        "message_update/<int:pk>/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message_delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path("client_create/", ClientCreateView.as_view(), name="client_create"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path(
        "client_detail/<int:pk>",
        cache_page(60)(ClientDetailView.as_view()),
        name="client_detail",
    ),
    path("client_update/<int:pk>", ClientUpdateView.as_view(), name="client_update"),
    path("client_delete/<int:pk>", ClientDeleteView.as_view(), name="client_delete"),
    path("attempts/", AttemptListView.as_view(), name="attempt_list")
]

mailing/models.py
from django.db import models
from users.models import User

NULLABLE = {"null": True, "blank": True}


class Client(models.Model):
    """Клиент сервиса"""

    name = models.CharField(
        max_length=255, verbose_name="ФИО", help_text="Введите имя клиента"
    )
    email = models.EmailField(
        max_length=100, verbose_name="Почта для рассылки", help_text="Заполните почту"
    )
    comment = models.TextField(max_length=250, verbose_name="Комментарий", **NULLABLE)
    autor = models.ForeignKey(
        User, verbose_name="автор", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Message(models.Model):
    """Сообщение для рассылки"""

    title = models.CharField(max_length=100, verbose_name="Тема письма")
    content = models.TextField(max_length=500, verbose_name="Содержание письма")
    autor = models.ForeignKey(
        User, verbose_name="автор", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["title"]

    def __str__(self):
        return self.title


class Mailing(models.Model):
    """Рассылка"""

    is_active = models.BooleanField(default=True, verbose_name="Активность рассылки")
    date_of_first_mail = models.DateTimeField(verbose_name="Дата отправки")
    date_of_last_mail = models.DateTimeField(verbose_name="Дата окончания рассылки", **NULLABLE)
    periodicity = models.CharField(
        max_length=5,
        verbose_name="Периодичность",
        choices={"day": "Раз в день", "week": "Раз в неделю", "month": "Раз в месяц"},
    )
    status = models.CharField(
        max_length=8,
        verbose_name="Статус рассылки",
        choices={"new": "Создана", "active": "Запущена", "complete": "Завершена"},
    )
    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        verbose_name="Сообщение",
        help_text="Выберите сообщение",
    )
    clients = models.ManyToManyField(Client, verbose_name="Клиенты")
    autor = models.ForeignKey(
        User, verbose_name="автор", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ["date_of_first_mail"]
        permissions = [
            ("can_view_mailing", "Can view mailing"),
            ("can_disable_mailing", "Can disable mailing"),
        ]

    def __str__(self):
        return str(self.date_of_first_mail)


class Attempt(models.Model):
    """Попытка отправки письма"""

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата первой попытки"
    )
    status = models.BooleanField(verbose_name="Статус попытки")
    server_response = models.TextField(verbose_name="Ответ сервера", **NULLABLE)
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        verbose_name="Рассылка",
        related_name="attempts",
        **NULLABLE
    )

    class Meta:
        verbose_name = "Попытка отправки"
        verbose_name_plural = "Попытки отправки"
        ordering = ["-created_at"]

    def __str__(self):
        return str(self.created_at)

mailing/forms.py
from django.forms import ModelForm, BooleanField, DateTimeField
from mailing.models import Message, Mailing, Client
from django.forms import ModelForm
from django.forms.widgets import CheckboxInput, Select, DateTimeInput
from users.models import User


class StyleFormMixin(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, CheckboxInput):
                field.widget.attrs["class"] = "form-check-input"
            elif isinstance(field.widget, Select):
                field.widget.attrs["class"] = "form-select"
            else:
                field.widget.attrs["class"] = "form-control"

            if isinstance(field.widget, DateTimeInput):
                field.widget.input_type = "datetime-local"


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("autor",)


class MailingForm(StyleFormMixin, DateTimeField, ModelForm):
    class Meta:
        model = Mailing
        exclude = ("autor", "is_active", "status")


class ModeratorMailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        fields = ("is_active",)


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ("autor",)

mailing/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)
from blog.services import get_blog_from_cache
from mailing.forms import MessageForm, MailingForm, ClientForm, ModeratorMailingForm
from mailing.models import Mailing, Message, Client, Attempt


class IndexView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["count_mailing"] = len(Mailing.objects.all())
        context_data["count_active_mailing"] = len(
            Mailing.objects.filter(is_active=True)
        )
        context_data["clients"] = len(Client.objects.all())
        context_data["blog_list"] = random.sample(
            list(get_blog_from_cache()), len(list(get_blog_from_cache()))
        )[:3]
        return context_data



class MessageListView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    model = Message


class MessageDetailView(LoginRequiredMixin,PermissionRequiredMixin, DetailView):
    login_url = "users:login"
    model = Message
    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user

class MessageCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.autor = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    login_url = "users:login"
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class MessageDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    login_url = "users:login"
    model = Message
    success_url = reverse_lazy("mailing:message_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class MailingListView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    model = Mailing


class MailingDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    login_url = "users:login"
    model = Mailing
    form_class = MailingForm

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user or user.has_perm("mailing.can_disable_mailing")


class MailingCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.autor = user
        mailing.status = "new"
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user or user.has_perm("mailing.can_disable_mailing")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.autor:
            return MailingForm
        elif user.has_perm("mailing.can_disable_mailing"):
            return ModeratorMailingForm
        raise PermissionDenied

    def form_valid(self, form):
        mailing = form.save()
        mailing.status = "new"
        mailing.save()
        return super().form_valid(form)


class MailingDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    login_url = "users:login"
    model = Mailing
    success_url = reverse_lazy("mailing:index")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class ClientCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.autor = user
        mailing.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = "users:login"
    model = Client
    success_url = reverse_lazy("mailing:client_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class ClientListView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client


class ClientDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user

class AttemptListView(ListView):
    model = Attempt

mailing/templates/mailing/attempt_list.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<h3>
    Попытки рассылок
</h3>
<div class="row row-cols-md-3 text-center ">
    <div class="col themed-grid-col "><h6>Тема сообщения</h6></div>
    <div class="col themed-grid-col "><h6>Статус рассылки</h6></div>
    <div class="col themed-grid-col "><h6>Последняя попытка</h6></div>
</div>
{% for attempt in object_list %}
    <div class="row row-cols-md-3 text-center border">
        <div class="container-fluid themed-container text-center border"><a>{{ attempt.mailing.message}}</a></div>
        <div class="container-fluid themed-container text-center border"><a>{% if attempt.status %}Отправлено успешно{% else %} {{ attempt.server_response }}{% endif %}</a></div>
        <div class="container-fluid themed-container text-center border"><a>{{ attempt.created_at }}</a></div>
    </div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.theme}} </h4>
                </div>
                <div class="card-body">
                    <form method="post">{% csrf_token %}
                        <p>Вы уверены, что хотите удалить клиента {object}}?</p>
                    {{ form }}
                        <input class="btn btn-primary" type="submit" value="Да">
                        <a class="btn btn-primary" href="{% url 'mailing:client_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.name}} </h4>
                </div>
                <div class="card-body">
                    <p class="card-text">Почта: {{object.email}}</p>
                    <p class="card-text">Комментарий: {{object.comment}}</p>
                    <a class="btn btn-primary" href="{% url 'mailing:client_list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/index.html' %}
{% block content %}
    <div class="container">
        <form class="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
            <div class="col-8">
                <div class="card">
                    {% if object %}
                        <p class="card-text">Редактирование</p>
                    {% else %}
                        <p class="card-text">Создание</p>
                    {% endif %}
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a class="btn btn-primary" href="{% url 'mailing:message_list' %}" role="button">Отмена</a>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<h3>
    Клиенты
</h3>
<div class="row row-cols-md-4 text-center">
    <div class="col themed-grid-col"><h6>ФИО</h6></div>
    <div class="col themed-grid-col"><h6>Почта</h6></div>
    <div class="col themed-grid-col"><h6>Комментарий</h6></div>
</div>
{% for client in object_list %}
    <div class="row row-cols-md-4 text-center border">
        <div class="container-fluid themed-container text-center border"><a>{{ client.name }}</a></div>
        <div class="container-fluid themed-container text-center border"><a>{{ client.email }}</a></div>
        <div class="container-fluid themed-container text-center border"><a>{{ client.comment }}</a></div>
        <div class="container-fluid themed-container text-center border">
            <div class="btn-group">
                <a class="btn btn-primary" href="{% url 'mailing:client_detail' client.pk %}"
                   role="button">Посмотреть</a>
                <a class="btn btn-primary" href="{% url 'mailing:client_update' client.pk %}"
                   role="button">Изменить</a>
                <a class="btn btn-primary" href="{% url 'mailing:client_delete' client.pk %}"
                   role="button">Удалить</a>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/index.html
{% load static %}
{% include 'includes/inc_style.html' %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mailing</title>
    {% include 'includes/inc_header.html' %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">
            Mailing
        </h1>
        <p class="lead">Mailing - это отличный вариант для рассылок</p>
    </div>
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                {% if user.is_superuser %}
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/admin/">В админку</a></li>
                </ul>
                {% endif %}
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</html>

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.theme}} </h4>
                </div>
                <div class="card-body">
                    <form method="post">{% csrf_token %}
                    <p>Вы уверены, что хотите удалить сообщение "{{ object }}"?</p>
                    {{ form }}
                        <input class="btn btn-primary" type="submit" value="Да">
                        <a class="btn btn-primary" href="{% url 'mailing:index' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.message_id}} </h4>
                </div>
                <div class="card-body">
                    <p class="card-text">Статус: {{object.get_status_display}}</p>
                    <p class="card-text">Дата отправки: {{object.date_of_first_mail}}</p>
                    <p class="card-text">Периодичность: {{object.get_periodicity_display}}</p>
                    <p class="card-text">Содержание письма: {{object.message_id.content}}</p>
                    <p class="card-text">Клиенты: {{object.client_id.name}}</p>
                    <p class="card-text">Автор: {{object.autor}}</p>
                    <a class="btn btn-primary" href="{% url 'mailing:index' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/index.html' %}
{% block content %}
    <div class="container">
        <form class="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
            <div class="col-8">
                <div class="card">
                    {% if object %}
                        <p class="card-text">Редактирование</p>
                    {% else %}
                        <p class="card-text">Создание</p>
                    {% endif %}
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                    <a class="btn btn-primary" href="{% url 'mailing:mailing_list' %}" role="button">Отмена</a>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<h3>
    Рассылки
</h3>
<div class="row row-cols-md-4 text-center ">
    <div class="col themed-grid-col "><h6>Тема</h6></div>
    <div class="col themed-grid-col "><h6>Статус отправки</h6></div>
    <div class="col themed-grid-col "><h6>Дата отправки</h6></div>
    <div class="col themed-grid-col"><h6>Взаимодействие</h6></div>
</div>
{% for mailing in object_list %}
            {% if mailing.autor == user or perms.mailing.can_view_mailing %}
    <div class="row row-cols-md-4 text-center border">
        <div class="container-fluid themed-container text-center border"><a>{{ mailing.message.title }}</a></div>
        <div class="container-fluid themed-container text-center border"><a>{{ mailing.get_status_display}}</a></div>
        <div class="container-fluid themed-container text-center border"><a>{{ mailing.date_of_first_mail}}</a></div>
        <div class="container-fluid themed-container border">
            <div class="btn-group">
                 <a class="btn btn-primary" href="{% url 'mailing:mailing_detail' mailing.pk %}"
                                   role="button">Посмотреть</a>
                                <a class="btn btn-primary" href="{% url 'mailing:mailing_update' mailing.pk %}"
                                   role="button">Изменить</a>
                {% if mailing.autor == user %}
                                <a class="btn btn-primary" href="{% url 'mailing:mailing_delete' mailing.pk %}"
                                   role="button">Удалить</a>
                   {% endif %}
            </div>
        </div>
    </div>
    {% endif %}
{% endfor %}
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.theme}} </h4>
                </div>
                <div class="card-body">
                    <form method="post">{% csrf_token %}
                    <p>Вы уверены, что хотите удалить сообщение "{{ object }}"?</p>
                    {{ form }}
                        <input class="btn btn-primary" type="submit" value="Да">
                        <a class="btn btn-primary" href="{% url 'mailing:message_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Тема письма: {{object.title}} </h4>
                </div>
                <div class="card-body">
                    <p class="card-text">Содержание: {{object.content}}</p>
                    <a class="btn btn-primary" href="{% url 'mailing:message_list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/index.html' %}
{% block content %}
    <div class="container">
        <form class="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-success">
                        Создать
                    </button>
                    <a class="btn btn-primary" href="{% url 'mailing:message_list' %}" role="button">Отмена</a>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<h3>
    Сообщения
</h3>
<div class="row row-cols-md-3 text-center ">
    <div class="col themed-grid-col "><h6>Тема</h6></div>
    <div class="col themed-grid-col "><h6>Содержание</h6></div>
    <div class="col themed-grid-col "><h6>Взаимодействия</h6></div>
</div>
{% for message in object_list %}
            {% if message.autor == user %}
    <div class="row row-cols-md-3 text-center border">
        <div class="container-fluid themed-container text-center border"><a>{{ message.title }}</a></div>
        <div class="container-fluid themed-container text-center border"><a>{{ message.content |slice:"100" }}</a></div>
        <div class="container-fluid themed-container text-center border">
            <div class="btn-group ">
                 <a class="btn btn-primary" href="{% url 'mailing:message_detail' message.pk %}"
                                   role="button">Посмотреть</a>
                                <a class="btn btn-primary" href="{% url 'mailing:message_update' message.pk %}"
                                   role="button">Изменить</a>
                                <a class="btn btn-primary" href="{% url 'mailing:message_delete' message.pk %}"
                                   role="button">Удалить</a>
            </div>
        </div>
    </div>
    {% endif %}
{% endfor %}
{% endblock %}