blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogUpdateView,
    BlogListView,
    BlogDetailView,
    BlogDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<slug>/", BlogDetailView.as_view(), name="blog_view"),
    path("update/<slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<slug>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="index")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from slugify import slugify
from users.models import User


# Create your models here.
class Blog(models.Model):
    title = models.CharField(
        max_length=100, verbose_name="Заголовок", help_text="Введите заголовок."
    )
    content = models.TextField(
        verbose_name="Содержание", help_text="Введите текст статьи."
    )
    slug = models.CharField(max_length=100, unique=True, blank=True)
    image = models.ImageField(
        upload_to="media/",
        verbose_name="Изображение",
        help_text="Загрузите изображение статьи.",
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True, verbose_name="Опубликовано")
    views = models.IntegerField(default=0, verbose_name="Просмотры")

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ["-created_at", "-status"]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

blog/forms.py
from django.forms import ModelForm, forms, BooleanField

from blog.models import Blog


class StyleFormMixin(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        exclude = ("slug", "created_at", "views", "status")

blog/views.py
from django.urls import reverse_lazy
from blog.forms import BlogForm
from blog.models import Blog
from django.views import generic
from blog.services import get_blog_from_cache


# Create your views here.


class BlogDetailView(generic.DetailView):
    model = Blog
    object = None

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogListView(generic.ListView):
    model = Blog

    def get_queryset(self):
        return get_blog_from_cache()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        status_list = Blog.objects.filter(status="True").order_by("-created_at")
        context["status_list"] = status_list
        return context


class BlogDeleteView(generic.DeleteView):
    model = Blog
    success_url = reverse_lazy("blog:blog_list")


class BlogUpdateView(generic.UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def get_success_url(self):
        return reverse_lazy("blog:blog_view", args=[self.kwargs["slug"]])


class BlogCreateView(generic.CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy("blog:blog_list")

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            from slugify import slugify

            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def form_user(self, form):
        blog = form.save()
        blog.autor = self.request.user
        blog.save()
        return super().form_valid(form)

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
    {% load static %}
    <div class="container">
        <div class="row text-center">
            <div class="col-10">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.theme }} </h4>
                    </div>
                    <div class="card-body">
                        <form method="post">{% csrf_token %}
                            <p>Вы уверены, что хотите удалить статью {object}}?</p>
                            {{ form }}
                            <input class="btn btn-primary" type="submit" value="Конечно">
                            <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-10">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{object.title}} </h4>
                </div>
                <div class="card-body">
                    {% include 'includes/inc_image.html' %}
                    <p class="card-text">Содержимое: {{object.content}}</p>
                    <p class="card-text">Дата создания: {{object.created_at}}</p>
                    <p class="card-text">Кол-во просмотров: {{object.views}}</p>
                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
    <div class="container">
        <div class="row text">
            <div class="col-12">
                <div class="row">
                    <div class="col-8">
                        <div class="card">
                            <div class="card-body">
                                <form class="text-body-color mb-3 form-control" method="post"
                                      enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button type="submit" class="btn btn-success">
                                        {% if object %}
                                            Сохранить
                                        {% else %}
                                            Создать
                                        {% endif %}
                                    </button>
                                    <a class="btn btn-primary" href="{% url 'blog:blog_list' %}"
                                       role="button">Отмена</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
    <div class="container">
        <div class="row text-center">
            <a class="btn btn-outline-primary mx-auto" href="{% url 'blog:blog_create' %}">Создать блог</a>
            <div class="pb-4"></div>
            {% for object in status_list %}
                <div class="col-3">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                        </div>
                        <div class="card-body">
                            {% include 'includes/inc_image.html' %}
                            <p class="text-start">{{ object.content  |slice:"100" }}</p>
                            <h1 class="card-title pricing-card-title"></h1>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-outline-primary"
                                       href="{% url 'blog:blog_view' object.slug %}"
                                       role="button">Подробнее</a>
                                    <a class="btn btn-sm btn-outline-success"
                                       href="{% url 'blog:blog_update' object.slug %}"
                                       role="button">Изменить</a>
                                    <a class="btn btn-sm btn-outline-danger"
                                       href="{% url 'blog:blog_delete' object.slug %}"
                                       role="button">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}