blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogUpdateView,
    BlogListView,
    BlogDetailView,
    BlogDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<slug>/", BlogDetailView.as_view(), name="blog_view"),
    path("update/<slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<slug>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="index")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    email_verification,
    RecoveryPasswordView,
    UserProfileView, UserUpdateView, UserListView
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path(
        "active_login/",
        LoginView.as_view(template_name="login_after_activate.html"),
        name="active_login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("activate/<str:token>/", email_verification, name="activate"),
    path("recovery/", RecoveryPasswordView.as_view(), name="recovery"),
    path(
        "profile/<int:pk>/", UserProfileView.as_view(), name="profile"
    ),
    path("profile_list/", UserListView.as_view(), name="profile_list"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="profile_update")
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone_number = PhoneNumberField(
        null=True, blank=True, verbose_name="Номер телефона"
    )
    country = models.CharField(
        max_length=50, verbose_name="Страна", null=True, blank=True
    )
    photo = models.ImageField(
        upload_to="users/photos/",
        verbose_name="Фото",
        help_text="Загрузите своё фото.",
        null=True,
        blank=True,
    )
    token = models.CharField(
        max_length=100, verbose_name="Токен", null=True, blank=True
    )
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"
        permissions = [
            ("can_edit_is_active", "Может блокировать пользователя"),
            ("can_view_users", "Может просматривать пользователей"),
        ]

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.forms import ModelForm
from django.forms.widgets import CheckboxInput, Select, DateTimeInput
from users.models import User


class StyleFormMixin(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, CheckboxInput):
                field.widget.attrs["class"] = "form-check-input"
            elif isinstance(field.widget, Select):
                field.widget.attrs["class"] = "form-select"
            else:
                field.widget.attrs["class"] = "form-control"

            if isinstance(field.widget, DateTimeInput):
                field.widget.input_type = "datetime-local"


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = (
            "email",
            "password1",
            "password2",
        )

class UserUpdateForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "last_name")
        exclude = ("password1", "password2")

users/views.py
import secrets
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from django.utils.crypto import get_random_string
from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/activate/{token}/"
        send_mail(
            subject="Активация аккаунта",
            message=f"Для активации вашего аккаунта перейдите по ссылке: {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("users:active_login"))


class RecoveryPasswordView(PasswordResetView):
    template_name = "users/recovery_password.html"
    form_class = PasswordResetForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        email = form.cleaned_data["email"]
        user = User.objects.get(email=email)
        if user:
            password = get_random_string(
                length=10,
                allowed_chars="abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789",
            )
            user.set_password(password)
            user.save(update_fields=["password"])
            send_mail(
                subject="Сброс пароля",
                message=f" Ваш новый пароль {password}",
                from_email=EMAIL_HOST_USER,
                recipient_list=[user.email],
            )
        return redirect(reverse("users:login"))


class UserProfileView(LoginRequiredMixin, DetailView):
    login_url = "users:login"
    model = User
    template_name = "users/profile.html"

class UserUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "users:login"
    model = User
    form_class = UserUpdateForm
    success_url = reverse_lazy("users:profile_list")

class UserListView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    model = User

users/templates/users/profile.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                </div>
                <div class="card-body">
                    <p class="card-text">email: {{user.email}}</p>
                    <p class="card-text">Номер телефона: {{user.phone_number}}</p>
                    <p class="card-text">Страна: {{user.country}}</p>
                    <a class="btn btn-primary" href="{% url 'mailing:index' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/recovery_password.html
{% extends 'mailing/index.html' %}
{% include 'includes/inc_style.html' %}
{% block content %}
<div class="container">
    <form class ="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-success">
                    Отправить письмо
                </button>
                <a class="btn btn-primary" href="{% url 'mailing:index' %}" role="button">Отмена</a>
                </div>
            </div>
    </form>
</div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/index.html' %}
{% include 'includes/inc_style.html' %}
{% block content %}
<div class="container">
    <form class ="text-body-color mb-3 form-control" method="post" enctype="multipart/form-data">
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                {% if object %}
                <button type="submit" class="btn btn-success">
                    Зарегистрироваться
                </button>
                {% else %}
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'users:profile_list' %}" role="button">Отмена</a>
                </div>
            </div>
    </form>
</div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'mailing/index.html' %}
{% load tags %}
{% block content %}
<h3>
Пользователи сервиса
</h3>
<div class="row row-cols-md-4 text-center ">
    <div class="col themed-grid-col "><h6>Почта</h6></div>
    <div class="col themed-grid-col "><h6>Номер телефона</h6></div>
    <div class="col themed-grid-col "><h6>Активность</h6></div>
    <div class="col themed-grid-col"><h6>Взаимодействие</h6></div>
</div>
{% for user in user_list %}
    <div class="row row-cols-md-4 text-center border">
        <div class="container-fluid themed-container text-center border"><a>{{ user.email }}</a></div>
        <div class="container-fluid themed-container text-center border"><a>{{ user.phone_number}}</a></div>
        <div class="container-fluid themed-container text-center border"><a>{{ user.is_active}}</a></div>
        <div class="container-fluid themed-container border">
            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'users:profile_update' user.pk %}"
                                   role="button">Изменить</a>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}