blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import (
    BlogCreateView,
    BlogUpdateView,
    BlogListView,
    BlogDetailView,
    BlogDeleteView,
)

app_name = BlogConfig.name

urlpatterns = [
    path("create/", BlogCreateView.as_view(), name="blog_create"),
    path("", BlogListView.as_view(), name="blog_list"),
    path("view/<slug>/", BlogDetailView.as_view(), name="blog_view"),
    path("update/<slug>/", BlogUpdateView.as_view(), name="blog_update"),
    path("delete/<slug>/", BlogDeleteView.as_view(), name="blog_delete"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mailing.urls", namespace="index")),
    path("users/", include("users.urls", namespace="users")),
    path("blog/", include("blog.urls", namespace="blog")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from mailing.apps import MailingConfig
from mailing.views import (
    MailingCreateView,
    MailingDetailView,
    MailingDeleteView,
    MailingUpdateView,
    MailingListView,
    ClientCreateView,
    ClientListView,
    ClientDetailView,
    ClientUpdateView,
    ClientDeleteView,
    MessageCreateView,
    MessageListView,
    MessageDetailView,
    MessageUpdateView,
    MessageDeleteView,
    IndexView, AttemptListView,
)

app_name = MailingConfig.name

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("mailings/", MailingListView.as_view(), name="mailing_list"),
    path("create/", MailingCreateView.as_view(), name="mailing_create"),
    path("update/<int:pk>", MailingUpdateView.as_view(), name="mailing_update"),
    path("delete/<int:pk>", MailingDeleteView.as_view(), name="mailing_delete"),
    path(
        "mailing/<int:pk>",
        cache_page(60)(MailingDetailView.as_view()),
        name="mailing_detail",
    ),
    path("client_create/", ClientCreateView.as_view(), name="client_create"),
    path("client_list/", ClientListView.as_view(), name="client_list"),
    path(
        "client_detail/<int:pk>/",
        cache_page(60)(ClientDetailView.as_view()),
        name="client_detail",
    ),
    path("client_update/<int:pk>/", ClientUpdateView.as_view(), name="client_update"),
    path("client_delete/<int:pk>/", ClientDeleteView.as_view(), name="client_delete"),
    path("message_create/", MessageCreateView.as_view(), name="message_create"),
    path("messages/", MessageListView.as_view(), name="message_list"),
    path(
        "message_detail/<int:pk>/",
        cache_page(60)(MessageDetailView.as_view()),
        name="message_detail",
    ),
    path(
        "message_update/<int:pk>/", MessageUpdateView.as_view(), name="message_update"
    ),
    path(
        "message_delete/<int:pk>/", MessageDeleteView.as_view(), name="message_delete"
    ),
    path("client_create/", ClientCreateView.as_view(), name="client_create"),
    path("clients/", ClientListView.as_view(), name="client_list"),
    path(
        "client_detail/<int:pk>",
        cache_page(60)(ClientDetailView.as_view()),
        name="client_detail",
    ),
    path("client_update/<int:pk>", ClientUpdateView.as_view(), name="client_update"),
    path("client_delete/<int:pk>", ClientDeleteView.as_view(), name="client_delete"),
    path("attempts/", AttemptListView.as_view(), name="attempt_list")
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import (
    UserCreateView,
    email_verification,
    RecoveryPasswordView,
    UserProfileView, UserUpdateView, UserListView
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path(
        "active_login/",
        LoginView.as_view(template_name="login_after_activate.html"),
        name="active_login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("activate/<str:token>/", email_verification, name="activate"),
    path("recovery/", RecoveryPasswordView.as_view(), name="recovery"),
    path(
        "profile/<int:pk>/", UserProfileView.as_view(), name="profile"
    ),
    path("profile_list/", UserListView.as_view(), name="profile_list"),
    path("update/<int:pk>/", UserUpdateView.as_view(), name="profile_update")
]

mailing/models.py
from django.db import models
from users.models import User

NULLABLE = {"null": True, "blank": True}


class Client(models.Model):
    """Клиент сервиса"""

    name = models.CharField(
        max_length=255, verbose_name="ФИО", help_text="Введите имя клиента"
    )
    email = models.EmailField(
        max_length=100, verbose_name="Почта для рассылки", help_text="Заполните почту"
    )
    comment = models.TextField(max_length=250, verbose_name="Комментарий", **NULLABLE)
    autor = models.ForeignKey(
        User, verbose_name="автор", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Клиент"
        verbose_name_plural = "Клиенты"
        ordering = ["name"]

    def __str__(self):
        return self.name


class Message(models.Model):
    """Сообщение для рассылки"""

    title = models.CharField(max_length=100, verbose_name="Тема письма")
    content = models.TextField(max_length=500, verbose_name="Содержание письма")
    autor = models.ForeignKey(
        User, verbose_name="автор", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"
        ordering = ["title"]

    def __str__(self):
        return self.title


class Mailing(models.Model):
    """Рассылка"""

    is_active = models.BooleanField(default=True, verbose_name="Активность рассылки")
    date_of_first_mail = models.DateTimeField(verbose_name="Дата отправки")
    date_of_last_mail = models.DateTimeField(verbose_name="Дата окончания рассылки", **NULLABLE)
    periodicity = models.CharField(
        max_length=5,
        verbose_name="Периодичность",
        choices={"day": "Раз в день", "week": "Раз в неделю", "month": "Раз в месяц"},
    )
    status = models.CharField(
        max_length=8,
        verbose_name="Статус рассылки",
        choices={"new": "Создана", "active": "Запущена", "complete": "Завершена"},
    )
    message = models.ForeignKey(
        Message,
        on_delete=models.CASCADE,
        verbose_name="Сообщение",
        help_text="Выберите сообщение",
    )
    clients = models.ManyToManyField(Client, verbose_name="Клиенты")
    autor = models.ForeignKey(
        User, verbose_name="автор", on_delete=models.SET_NULL, **NULLABLE
    )

    class Meta:
        verbose_name = "Рассылка"
        verbose_name_plural = "Рассылки"
        ordering = ["date_of_first_mail"]
        permissions = [
            ("can_view_mailing", "Can view mailing"),
            ("can_disable_mailing", "Can disable mailing"),
        ]

    def __str__(self):
        return str(self.date_of_first_mail)


class Attempt(models.Model):
    """Попытка отправки письма"""

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата первой попытки"
    )
    status = models.BooleanField(verbose_name="Статус попытки")
    server_response = models.TextField(verbose_name="Ответ сервера", **NULLABLE)
    mailing = models.ForeignKey(
        Mailing,
        on_delete=models.CASCADE,
        verbose_name="Рассылка",
        related_name="attempts",
        **NULLABLE
    )

    class Meta:
        verbose_name = "Попытка отправки"
        verbose_name_plural = "Попытки отправки"
        ordering = ["-created_at"]

    def __str__(self):
        return str(self.created_at)

mailing/forms.py
from django.forms import ModelForm, BooleanField, DateTimeField
from mailing.models import Message, Mailing, Client
from django.forms import ModelForm
from django.forms.widgets import CheckboxInput, Select, DateTimeInput
from users.models import User


class StyleFormMixin(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, CheckboxInput):
                field.widget.attrs["class"] = "form-check-input"
            elif isinstance(field.widget, Select):
                field.widget.attrs["class"] = "form-select"
            else:
                field.widget.attrs["class"] = "form-control"

            if isinstance(field.widget, DateTimeInput):
                field.widget.input_type = "datetime-local"


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        exclude = ("autor",)


class MailingForm(StyleFormMixin, DateTimeField, ModelForm):
    class Meta:
        model = Mailing
        exclude = ("autor", "is_active", "status")


class ModeratorMailingForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Mailing
        fields = ("is_active",)


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        exclude = ("autor",)

mailing/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    TemplateView,
)
from blog.services import get_blog_from_cache
from mailing.forms import MessageForm, MailingForm, ClientForm, ModeratorMailingForm
from mailing.models import Mailing, Message, Client, Attempt


class IndexView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["count_mailing"] = len(Mailing.objects.all())
        context_data["count_active_mailing"] = len(
            Mailing.objects.filter(is_active=True)
        )
        context_data["clients"] = len(Client.objects.all())
        context_data["blog_list"] = random.sample(
            list(get_blog_from_cache()), len(list(get_blog_from_cache()))
        )[:3]
        return context_data



class MessageListView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    model = Message


class MessageDetailView(LoginRequiredMixin,PermissionRequiredMixin, DetailView):
    login_url = "users:login"
    model = Message
    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user

class MessageCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def form_valid(self, form):
        message = form.save()
        user = self.request.user
        message.autor = user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    login_url = "users:login"
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy("mailing:message_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class MessageDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    login_url = "users:login"
    model = Message
    success_url = reverse_lazy("mailing:message_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class MailingListView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    model = Mailing


class MailingDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    login_url = "users:login"
    model = Mailing
    form_class = MailingForm

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user or user.has_perm("mailing.can_disable_mailing")


class MailingCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.autor = user
        mailing.status = "new"
        mailing.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy("mailing:mailing_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user or user.has_perm("mailing.can_disable_mailing")

    def get_form_class(self):
        user = self.request.user
        if user == self.object.autor:
            return MailingForm
        elif user.has_perm("mailing.can_disable_mailing"):
            return ModeratorMailingForm
        raise PermissionDenied

    def form_valid(self, form):
        mailing = form.save()
        mailing.status = "new"
        mailing.save()
        return super().form_valid(form)


class MailingDeleteView(LoginRequiredMixin,PermissionRequiredMixin, DeleteView):
    login_url = "users:login"
    model = Mailing
    success_url = reverse_lazy("mailing:index")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class ClientCreateView(LoginRequiredMixin, CreateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")

    def form_valid(self, form):
        mailing = form.save()
        user = self.request.user
        mailing.autor = user
        mailing.save()
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin,PermissionRequiredMixin, UpdateView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("mailing:client_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = "users:login"
    model = Client
    success_url = reverse_lazy("mailing:client_list")

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user


class ClientListView(LoginRequiredMixin, ListView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client


class ClientDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    login_url = "users:login"
    redirect_field_name = "redirect_to"
    model = Client

    def has_permission(self):
        obj = self.get_object()
        user = self.request.user
        return obj.autor == user

class AttemptListView(ListView):
    model = Attempt

mailing/templates/includes/inc_header.html
<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-white">Главная</a></li>
                <li><a href="{% url 'blog:blog_list' %}" class="nav-link px-2 text-white">Блог</a></li>
                <li><a href="{% url 'mailing:mailing_list' %}" class="nav-link px-2 text-white">Рассылки</a></li>
                <li><a href="{% url 'mailing:message_list' %}" class="nav-link px-2 text-white">Сообщения</a></li>
                <li><a href="{% url 'mailing:client_list' %}" class="nav-link px-2 text-white">Клиенты</a></li>
                {% if perms.users.can_view_users %}
                <li><a href="{% url 'users:profile_list' %}" class="nav-link px-2 text-white">Пользователи</a></li>
                {% endif %}
                <li><a href="{% url 'mailing:attempt_list' %}" class="nav-link px-2 text-white">Попытки рассылок</a></li>
            </ul>


            <div class="text-end">
                {% if user.is_authenticated %}
                <form action="{% url 'users:logout' %}" method="post">
                <a class="btn btn-primary" href="{% url 'mailing:mailing_create' %}" role="button">создать рассылку</a>
                <a class="btn btn-primary" href="{% url 'mailing:message_create' %}" role="button">добавить сообщение</a>
                <a class="btn btn-primary" href="{% url 'mailing:client_create' %}" role="button">добавить клиента</a>
                    {% csrf_token %}
                    <a href="{% url 'users:profile' request.user.pk%}">
                        <button type="button" class="btn btn-warning">{{user.email}}</button>
                    </a>
                    <button type="submit" class="btn btn-outline-light me-2">Выйти</button>
                </form>
                {% else %}
                <a href="{% url 'users:login' %}">
                    <button type="button" class="btn btn-outline-light me-2">Войти</button>
                </a>
                <a href="{% url 'users:register' %}">
                    <button type="button" class="btn btn-warning">Зарегистрироваться</button>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</header>

mailing/templates/includes/inc_image.html
{% load tags %}
{% load static %}
{% if blog.image %}
    <img class="w-100" alt="картинка" src="{{ blog.image | mymedia }}"
         onerror="this.onerror=null; this.src='{% static 'no_image.jpg' %}'">
{% elif object.image %}
    <img class="w-100" alt="картинка" src="{{ object.image | mymedia }}"
         onerror="this.onerror=null; this.src='{% static 'no_image.jpg' %}'">
{% elif blog.image %}
    <img class="w-100" alt="картинка" src="{{ blog.image | mymedia }}"
         onerror="this.onerror=null; this.src='{% static 'no_image.jpg' %}'">
{% elif users.photo %}
    <img class="w-100" alt="картинка" src="{{ users.photo | mymedia }}"
         onerror="this.onerror=null; this.src='{% static 'no_image.jpg' %}'">
{% else %}
    <img class="w-100" alt="картинка" src="{% static 'no_image.jpg' %}">
{% endif %}

mailing/templates/includes/inc_style.html
{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
    }

    .bi {
        vertical-align: -.125em;
        fill: currentColor;
    }

    .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
    }

    .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

</style>